services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app/the_mooli_project
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A the_mooli_project.celery_app worker --loglevel=info
    working_dir: /app/the_mooli_project
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  celery_beat:
    build: .
    command: celery -A the_mooli_project.celery_app beat --loglevel=info
    working_dir: /app/the_mooli_project
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"